version: '3.9'
# TODO volumes and command should go to override compose file
services:
  app:
    build:
      context: app
    volumes:
      - type: bind
        source: ./app/
        target: /go/src/app/
    networks:
      nw:
    command: ["tail", "-f", "/dev/null"]
  web:
    image: nginx:latest
    # build:
      # context: web
      # args:
        # - XYZ
    ports:
      - target: 80
        published: 80
      - target: 443
        published: 443
    volumes:
      - type: bind
        source: ./web/certs
        target: /etc/nginx/certs
      - type: bind
        source: ./web/secure.conf
        target: /etc/nginx/conf.d/secure.conf
    networks:
      nw:
networks:
  nw:
